global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'users'
    target_groups:
      - targets: ['shopkeep.services.user:3001']
  - job_name: 'products'
    target_groups:
      - targets: ['shopkeep.services.products:3002']
  - job_name: 'carts'
    target_groups:
      - targets: ['shopkeep.services.carts:3003']
