global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'users'
    static_configs:
      - targets: ['shopkeep.services.user:3001']
  - job_name: 'products'
    static_configs:
      - targets: ['shopkeep.services.product:3002']
  - job_name: 'carts'
    static_configs:
      - targets: ['shopkeep.services.cart:3003']
